spring.application.name=SpringAIAgent

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=KEY

spring.ai.openai.chat.model=openrouter/free
spring.ai.model.chat=openai
spring.ai.model.embedding=ollama
spring.ai.ollama.embedding.model=nomic-embed-text

# Schema management & Vector space tuning
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

spring.datasource.url=jdbc:postgresql://localhost:5432/aidb
spring.datasource.username=user
spring.datasource.password=password

app.pdf-path=classpath:documents/sample.pdf

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Disable the Ollama chat auto-configuration so it doesn't conflict with OpenRouter
spring.ai.ollama.chat.enabled=false
