spring.application.name=SpringAIAgent

# Ollama Connection Configuration
#spring.ai.ollama.base-url=http://localhost:11434

# Define Chat Model
#spring.ai.ollama.chat.options.model=llama3

# Custom path to access the Swagger UI dashboard html page
springdoc.swagger-ui.path=/swagger-ui.html

# Custom path to download the raw JSON structure configuration definition 
springdoc.api-docs.path=/v3/api-docs

# Define Embedding Model 
spring.ai.ollama.embedding.options.model=nomic-embed-text
# Tell Spring AI to use the 1B model for generating answers
spring.ai.ollama.chat.model=llama3.2:1b

# Application configuration custom properties
app.pdf-path=classpath:documents/sample.pdf

# Standard Spring DataSource Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/aidb
spring.datasource.username=user
spring.datasource.password=password

# Spring AI PGVector Configuration
# Automatically creates the vector table (`vector_store`) if it doesn't exist
spring.ai.vectorstore.pgvector.initialize-schema=true

# Match this to your embedding model dimension 
# (nomic-embed-text uses 768, text-embedding-ada-002 uses 1536)
spring.ai.vectorstore.pgvector.dimensions=768

# Fix: Change COSINE to COSINE_DISTANCE
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE